version: '3.8'
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - CMC_API_KEY=${CMC_API_KEY}
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
