version: '3.8'

services:
  app:
    build: .
    image: my_data605_project-notebook
    environment:
      - CMC_API_KEY=${CMC_API_KEY}
    volumes:
      - ./data:/app/data  # Maps the 'data' directory on your host to '/app/data' inside the container
    ports:
      - "8888:8888"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  data:
    driver: local
